### ISSUE TITLE
add composer.json

### ISSUE THREAD

**Issue by wernerkrauss** [NightJar/ssrigging-slug#1]
How about making this great small module installable with composer?

**Comment by NightJar** [comment]
Yes, a fine request and a plan that had remained as such for admittedly too long. Similarly this issue has remained open too long, since you and I both know this was finally done 2 months ago! (33d804cce2a3841d2b0a393831b76da6076b30b1)

So now it is time to tidy up. Have a good Christmas Werner :)

**Comment by wernerkrauss** [comment]
Thanks for the greetings, absolutely this was a good choice.

Quite silent in IRC now...

You could also close this issue, but now i close it and wish you the best for xmas and 2016!
