### ISSUE TITLE
Update to SS4

### ISSUE THREAD

**Issue by wernerkrauss** [NightJar/ssrigging-slug#3]
Any plans to update this module to SS4?

**Comment by NightJar** [comment]
Yeah I probably should huh :)
It's the weekend tomorrow, I guess we'll see...

**Comment by jinjie** [comment]
@NightJar Have you started on the SS4 upgrade? I use this module quite extensively in a few projects. I might be able to help out on this.

**Comment by NightJar** [comment]
Indeed I have, please keep an eye out, should be something ready shortly :)

**Comment by NightJar** [comment]
Hi team, @wernerkrauss, @jinjie 
Sorry this took so long!
However I believe I have completed the upgrade & also added some new features. Please feel free to test it on the [ss4upgrade](https://github.com/NightJar/ssrigging-slug/tree/ss4upgrade) branch. I'd like to leave this issue open until I'm happy that some exploratory testing (ie. real use on real projects), when I'll merge into master and tag the stable release.

Related:
https://github.com/silverstripe/silverstripe-framework/pull/8444
https://github.com/silverstripe/silverstripe-framework/issues/8443

**Comment by NightJar** [comment]
Thanks for the correspondence in https://github.com/NightJar/ssrigging-slug/issues/5#issuecomment-450286720 @jinjie - I've tagged a 2.0.0 release and will close this off now :)
