### ISSUE TITLE
Weird behavior in getting $fieldToSlug in SS4

### ISSUE THREAD

**Issue by jinjie** [NightJar/ssrigging-slug#5]
I extended 2 dataobjects:

A_DataObject: Slug FirstName
B_DataObject: Slug Title

When saving B_DataObject, $fieldToSlug for some reason returns FirstName. With the wrong field, it cannot find FirstName, and therefore URLSlug is always empty.

Did some troubleshooting, dumped onBeforeWrite when saving B_DataObject, $this->getOwner() returns B_DataObject, but further inspection found that "FirstName" in $fieldToSlug.

Ref #3

**Comment by jinjie** [comment]
My mistake. Problems with my code.

**Comment by NightJar** [comment]
I feel like there's an opportunity to improve documentation here @jinjie - would you be willing to share details?

Was it perhaps that you were applying the extension through `yml` config?
If so, then I should make it clearer that _with the current status of SS4_ all config is instantiated as a singleton **regardless of constructor parameters** - meaning that the first extension applied (i.e. for `A_DataObject` in your case) will have the same parameters applied to all subsequent `slug` extensions defined.

Very unfortunate.

Related PR that I'd hoped to get into 4.3 (but didn't) to help rectify this:
https://github.com/silverstripe/silverstripe-framework/pull/8444

**Comment by jinjie** [comment]
@NightJar 

I have tried applying the extension through yml config and $extensions.

When this issue was created initially, I tried applying the extension by:

```
MarketPlaceListing:
  extensions:
    - NightJar\Slug\Slug('Title', null, true)
```

or

```
private static $extensions = array(
    "NightJar\\Slug\\Slug('Title', null, true)",
);
```

I then realised that I need to add `\\` prefix to the namespace to make it work, which I don't normally do for other extensions. Not sure if it is a bug or something I did to my code that require that prefix.

Any of of these works:

```
MarketPlaceListing:
  extensions:
    - \NightJar\Slug\Slug('Title', null, true)
```

or

```
private static $extensions = array(
    "\\NightJar\\Slug\\Slug('Title', null, true)",
);
```

I did not put my DataObject in any namespace.

**Comment by NightJar** [comment]
Hmm, that sure is strange, sorry I can't answer that @jinjie!
[I tested](http://sandbox.onlinephpfunctions.com/code/ebb5f52aad2de523e045d5f1e6121bc4b9e888a4) different types of quotations with the escape character, and couldn't see an issue from the PHP end of things (I'd expected the single backslash might be causing issue). The creation code is the default [injection instantiation method](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Core/Injector/InjectionCreator.php#L14), and I've tested both with and without a leading slash (to indicate root).
![image](https://user-images.githubusercontent.com/778003/50501914-961d1e00-0ac0-11e9-972a-4e1c841efb35.png)

Another way to get around this and be slightly more readable might be to use the inbuilt `::class` defecerencer (when in PHP), e.g.

```php
private static $extensions = [
    Slug::class . "('Title', null, true)",
];
```

How are you finding the upgrade anyway, have you used it on any projects yet, or is this the first upgrade attempt?

**Comment by jinjie** [comment]
> Another way to get around this and be slightly more readable might be to use the inbuilt `::class` defecerencer (when in PHP), e.g.

Yes! Why didn't I thought of that. 😆 

> How are you finding the upgrade anyway, have you used it on any projects yet, or is this the first upgrade attempt?

I have used the 76b61d9 branch for a couple SS4 projects now without any issues.

This issue is opened when I was upgrading a SS3 project to SS4 (first ss3 -> ss4 upgrade).

**Comment by NightJar** [comment]
Neat, thanks for letting me know it's working well for you :D
I've tagged 2.0.0 and merged the `ss4upgrade` branch into master. I've left the branch in place for now though to give you time to update your various `composer.json` requirements :)
